# Generated by Django 3.1.5 on 2021-01-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210116_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='portfolio/images/')),
                ('home_logo', models.ImageField(upload_to='portfolio/images/')),
            ],
        ),
    ]
