# Generated by Django 3.1.5 on 2021-01-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='des',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='port',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
